services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app/app.jar", "--server.address=0.0.0.0"]
    restart: unless-stopped
